### ISSUE TITLE
Issue with variable data.weightsTr, in learn_attributes_bagging.m

### ISSUE THREAD

**Issue by dutta1kartik3** [almazan/watts#5]
The variable data.weightsTr is not defined in any other file and is causing an error ("variable not defined") while trying to run the  main.m even though I am following the instructions mentioned in the Readme.md page on github.

**Comment by almazan** [comment]
Thanks Dutta for reporting this bug.

This variable was used for weighting the importance of the samples in the SVM training, which was no longer used in the final version of the method. I have removed all the occurrences of this variable in the script for learning the attributes, where the execution was crashing, so it should work now.
