### ISSUE TITLE
Running the Code with George Washington Dataset

### ISSUE THREAD

**Issue by dutta1kartik3** [almazan/watts#6]
Inside the datasets folder provided, there is only a single sub directory for the IAM dataset containing the queries.gtp and forms.gtp files. I am not able to download from the link provided(http://www.cvc.uab.es/~almazan/data/GW.tar.gz). Could you please look into it ?

**Comment by almazan** [comment]
I have uploaded again the GW dataset to the following link: https://www.dropbox.com/s/4wvkysd58bu63pt/GW.zip?dl=0

**Comment by sfikas** [comment]
The above link for GW isnt working.
A working link is
https://www.dropbox.com/s/ewz5c2gmxwjyokm/GW.zip?dl=0
from your other work.

**Comment by almazan** [comment]
Thanks a lot! I've just updated (once again) the link in the README file.
